/*
Script generated by Aqua Data Studio 9.0.14 on May-09-2011 01:49:59 PM
Database: null
Schema: <All Schemas>
*/

ALTER TABLE `order_t`
	DROP FOREIGN KEY `order_customer_fk`
GO
ALTER TABLE `order_t`
	DROP FOREIGN KEY `order_item_fk`
GO
DROP TABLE IF EXISTS `customer`
GO
DROP TABLE IF EXISTS `item`
GO
DROP TABLE IF EXISTS `order_t`
GO
CREATE TABLE `customer`  ( 
	`id`             	integer(15) UNSIGNED AUTO_INCREMENT NOT NULL,
	`title`          	varchar(4) NOT NULL,
	`surname`        	varchar(20) NOT NULL,
	`forename`       	varchar(20) NOT NULL,
	`telephone`      	varchar(15) NOT NULL,
	`fax`            	varchar(15) NULL,
	`email`          	varchar(30) NOT NULL,
	`building_number`	smallint(15) UNSIGNED NULL,
	`building_name`  	varchar(30) NULL,
	`address_line_1` 	varchar(30) NOT NULL,
	`address_line_2` 	varchar(30) NULL,
	`address_line_3` 	varchar(30) NULL,
	`postcode`       	varchar(7) NOT NULL,
	`country`        	varchar(20) NULL,
	PRIMARY KEY(`id`)
)
CHARACTER SET utf8
GO
CREATE TABLE `item`  ( 
	`id`         	integer(15) UNSIGNED AUTO_INCREMENT NOT NULL,
	`description`	varchar(80) NOT NULL,
	`price`      	float(10,0) UNSIGNED NOT NULL,
	`content`    	mediumtext CHARACTER SET utf8 NOT NULL,
	PRIMARY KEY(`id`)
)
CHARACTER SET utf8
GO
CREATE TABLE `order_t`  ( 
	`id`            	integer(15) UNSIGNED AUTO_INCREMENT NOT NULL,
	`customer_id`   	integer(15) UNSIGNED NOT NULL,
	`item_id`       	integer(15) UNSIGNED NOT NULL,
	`request_id`    	varchar(15) NOT NULL,
	`quantity`      	smallint(15) UNSIGNED NOT NULL,
	`date_placed`   	timestamp NOT NULL,
	`payment_method`	varchar(20) NOT NULL,
	`dispatched`    	bit(1) NOT NULL,
	PRIMARY KEY(`id`)
)
CHARACTER SET utf8
GO
ALTER TABLE `order_t`
	ADD CONSTRAINT `order_customer_fk`
	FOREIGN KEY(`customer_id`)
	REFERENCES `customer`(`id`)
GO
ALTER TABLE `order_t`
	ADD CONSTRAINT `order_item_fk`
	FOREIGN KEY(`item_id`)
	REFERENCES `item`(`id`)
GO
